name: PR Target + Fork Execution Test

on:
  pull_request_target:
    types: [opened, synchronize]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Show context
        run: |
          echo "=== CONTEXT ==="
          echo "event: $GITHUB_EVENT_NAME"
          echo "repo: $GITHUB_REPOSITORY"
          echo "sha: $GITHUB_SHA"
          echo "actor: $GITHUB_ACTOR"

      - name: Show if secret existsss
        env:
          SECRET_TEST: ${{ secrets.SECRET_TEST }}
        run: |
          if [ -z "$SECRET_TEST" ]; then
            echo "SECRET: NOT AVAILABLE"
          else
            echo "SECRET: AVAILABLE"
          fi

      - name: Checkout PR code (fork)
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Show repo files (fork code inside privileged context)
        run: |
          echo "=== FILES ==="
          ls -la
